### ISSUE TITLE
Need to find a way to install the exporter

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/charm-prometheus-hardware-exporter#12]
As we are no longer (at least not planing in the near future) using the exporter as snap, we should find an alternative to install the exporter.

**Comment by rgildein** [comment]
Why we don't want to use exporter as snap? What are reasons here?

To my this is not good idea, since snap provide good mechanism to make update. If we will go with Python package + using tagged version, we will need to make chance in charm if we want to update to latest version.

**Comment by jneo8** [comment]
It's because currently we can't give the required permission, which are mostly not allow to access if snap is strict level, to the snap. And there is no snap interface we can use.

And the classic snap's review process will be the blocker for us.
So our first step is make it as a simple service. The snap will be the next stage.
And the classic snap's review process will be the blocker for us.
So our first step is make it as a simple service. The snap will be the next stage.

> Why we don't want to use exporter as snap? What are reasons here?
> 
> To my this is not good idea, since snap provide good mechanism to make update. If we will go with Python package + using tagged version, we will need to make chance in charm if we want to update to latest version.


It's because currently we can't give the required permission, which are mostly not allow to access if snap is strict level, to the snap. And there is no snap interface we can use.

And the classic snap's review process will be the blocker for us.
So our first step is make it as a simple service. The snap will be the next stage.

**Comment by rgildein** [comment]
> And the classic snap's review process will be the blocker for us. So our first step is make it as a simple service. The snap will be the next stage.

I do not understand what do you mean by 'classic snap's review process will be the blocker for us'? If we will do snap eventually, why making so much changes now and than revert them back?

**Comment by chanchiwai-ray** [comment]
Per request, I've created the [request for class confinement](https://forum.snapcraft.io/t/request-for-classic-confinement-prometheus-hardware-exporter/35701), and hopefully someone will take a look later and approve (🤞) / reject it. In any case, it does not seems that we have time to complete the implementation using snap since we will be preparing a release next week.
